/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.14
 * Generated at: 2014-11-05 14:00:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <title>Home</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"./inc/css/reset.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"./inc/css/style.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"./inc/css/grid_12.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"./inc/css/slider.css\">\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Condiment' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <script src=\"./inc/js/jquery-1.7.min.js\"></script>\n");
      out.write("    <script src=\"./inc/js/jquery.easing.1.3.js\"></script>\n");
      out.write("     \n");
      out.write("     <!-- A ajouter partour \n");
      out.write("     \n");
      out.write("    <script type=\"text/javascript\" src=\"./inc/js/jquery-1.9.1.min.js\"></script>-->\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"./inc/js/jquery.leanModal.min.js\"></script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <script src=\"./inc/js/tms-0.4.x.js\"></script>\n");
      out.write("    <script>\n");
      out.write("\t\t$(document).ready(function(){\t\t\t\t   \t\n");
      out.write("\t\t\t$('.slider')._TMS({\n");
      out.write("\t\t\t\tshow:0,\n");
      out.write("\t\t\t\tpauseOnHover:true,\n");
      out.write("\t\t\t\tprevBu:false,\n");
      out.write("\t\t\t\tnextBu:false,\n");
      out.write("\t\t\t\tplayBu:false,\n");
      out.write("\t\t\t\tduration:1000,\n");
      out.write("\t\t\t\tpreset:'fade',\n");
      out.write("\t\t\t\tpagination:true,\n");
      out.write("\t\t\t\tpagNums:false,\n");
      out.write("\t\t\t\tslideshow:7000,\n");
      out.write("\t\t\t\tnumStatus:true,\n");
      out.write("\t\t\t\tbanners:'fromRight',\n");
      out.write("\t\t\t\twaitBannerAnimation:false,\n");
      out.write("\t\t\t\tprogressBar:false\n");
      out.write("\t\t\t})\t\t\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("\t<!--[if lt IE 8]>\n");
      out.write("       <div style=' clear: both; text-align:center; position: relative;'>\n");
      out.write("         <a href=\"http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode\">\n");
      out.write("           <img src=\"http://storage.ie6countdown.com/assets/100/./inc/images/banners/warning_bar_0000_us.jpg\" border=\"0\" height=\"42\" width=\"820\" alt=\"You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today.\" />\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("    <![endif]-->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("   \t\t<script type=\"text/javascript\" src=\"js/html5.js\"></script>\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/ie.css\">\n");
      out.write("\t<![endif]-->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div class=\"main\">\n");
      out.write("  <!--==============================header=================================-->\n");
      out.write("  \n");
      out.write("  \n");
      out.write("     <header>\n");
      out.write("        <h1><a href=\"index.jsp\"><img src=\"./inc/images/logo.png\" alt=\"\"></a>\n");
      out.write("        </h1>\n");
      out.write("        <section class=\"header-login\">\n");
      out.write("        <form name=\"login\" action=\"index_submit\" method=\"get\" accept-charset=\"utf-8\">\n");
      out.write("        <ul>\n");
      out.write("       <li><a href=\"#loginmodal\" id=\"modaltrigger\">S'identifier</a></li>\n");
      out.write("       <li><a href=\"inscription.jsp\">S'inscrire</a></li>\n");
      out.write("       \n");
      out.write("       \n");
      out.write("       <div id=\"loginmodal\" style=\"display:none;\">\n");
      out.write("       <center>\n");
      out.write("       <h1>Entrez Vos Identifiants</h1>\n");
      out.write("       </center>\n");
      out.write("       <br>\n");
      out.write("      \n");
      out.write("       <form id=\"loginform\" name=\"loginform\" method=\"post\" action=\"index.jsp\">\n");
      out.write("       \n");
      out.write("       <label for=\"username\">Email:</label>\n");
      out.write("       <input type=\"text\" name=\"username\" id=\"username\" class=\"txtfield\" tabindex=\"1\">\n");
      out.write("       \n");
      out.write("       <label for=\"password\">Mot de passe:</label>\n");
      out.write("       <input type=\"password\" name=\"password\" id=\"password\" class=\"txtfield\" tabindex=\"2\">\n");
      out.write("       \n");
      out.write("       <br>\n");
      out.write("       <center>\n");
      out.write("       <div class=\"center\"><input type=\"submit\" name=\"loginbtn\" id=\"loginbtn\" class=\"flatbtn-blu hidemodal\" value=\"Se Connecter\" tabindex=\"3\"></div>\n");
      out.write("       </center>\n");
      out.write("       </form>\n");
      out.write("       </div>\n");
      out.write("       <script type=\"text/javascript\">\n");
      out.write("       $(function(){\n");
      out.write("       $('#loginform').submit(function(e){\n");
      out.write("       return false;\n");
      out.write("       });\n");
      out.write("       \n");
      out.write("       $('#modaltrigger').leanModal({ top: 110, overlay: 0.45, closeButton: \".hidemodal\" });\n");
      out.write("       });\n");
      out.write("       </script>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        </ul>\n");
      out.write("        </form>\n");
      out.write("        </section>\n");
      out.write("        \n");
      out.write("        <div class=\"clear\"></div>    \n");
      out.write("        <nav class=\"box-shadow\">\n");
      out.write("            <div>\n");
      out.write("                <ul class=\"menu\">\n");
      out.write("                    <li class=\"home-page current\"><a href=\"index.jsp\"><span></span></a></li>\n");
      out.write("                    <li><a href=\"about.jsp\">A Propos De Nous</a></li>\n");
      out.write("                    <li><a href=\"services.jsp\">Nos Offres</a></li>\n");
      out.write("                    <li><a href=\"clients.jsp\">Nos Partenaires</a></li>\n");
      out.write("                    <li><a href=\"contacts.jsp\">Contacts</a></li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"social-icons\">\n");
      out.write("                    <span>Nous suivre:</span>\n");
      out.write("                    <a href=\"#\" class=\"icon-3\"></a>\n");
      out.write("                    <a href=\"#\" class=\"icon-2\"></a>\n");
      out.write("                    <a href=\"#\" class=\"icon-1\"></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"clear\"></div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("    </header>   \n");
      out.write("  <!--==============================content================================-->\n");
      out.write("    <section id=\"content\">\n");
      out.write("        <div id=\"slide\" class=\"box-shadow\">\t\t\n");
      out.write("            <div class=\"slider\">\n");
      out.write("                <ul class=\"items\">\n");
      out.write("                    <li><img src=\"./inc/images/slider-1.jpg\" alt=\"\" /><div class=\"banner\">Le Succes Garantie Pour Vos Ãtudes&nbsp;</div></li>\n");
      out.write("                    <li><img src=\"./inc/images/slider-2.jpg\" alt=\"\" /><div class=\"banner\">Des Professeurs QualifiÃ©s Ã Votre Disposition&nbsp;</div></li>\n");
      out.write("                    <li><img src=\"./inc/images/slider-3.jpg\" alt=\"\" /><div class=\"banner\">Des Cours PersonnalisÃ©s Selon Vos Besoins&nbsp;</div></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\t\n");
      out.write("        </div>\n");
      out.write("        <div class=\"container_12\">\n");
      out.write("          <div class=\"grid_12\">\n");
      out.write("            <div class=\"pad-0 border-1\">\n");
      out.write("                <h2 class=\"top-1 p0\">Nous Vous Ouvrons La Voie Du SuccÃ¨s!</h2>\n");
      out.write("                <p class=\"p2\">iSchool est une plateforme intÃ©ractive qui met Ã  la disposition d'Ã©lÃ¨ve, un large panel de cours virtuels. Que vous soyez collÃ¨gien ou Ã©tudiant en Ã©cole d'ingÃ©nieur, iSchool est fait pour vous! En effet des professeurs de collÃ¨ge, de lycÃ©e et universitaire, sÃ©lÃ©ctionnÃ©s par nos soins, vous attendent. </p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"wrap block-1 pad-1\">\n");
      out.write("                <div>\n");
      out.write("                    <h3>Les Meilleurs Pour Vous</h3>\n");
      out.write("                    <img src=\"./inc/images/page1-img1.jpg\" alt=\"\" class=\"img-border\">\n");
      out.write("                    <p>Nous selectionnons nous mÃªme les professeurs prÃ©sent sur le site. Ils sont choisis grÃ¢ce Ã  leur expÃ©rience.</p>\n");
      out.write("                    <a href=\"#\" class=\"button\">Plus</a>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <h3>deuxieme zone</h3>\n");
      out.write("                    <img src=\"./inc/images/page1-img2.jpg\" alt=\"\" class=\"img-border\">\n");
      out.write("                    <p>blabla</p>\n");
      out.write("                    <a href=\"#\" class=\"button\">Plus</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"last\">\n");
      out.write("                    <h3>troisieme zone</h3>\n");
      out.write("                    <img src=\"./inc/images/page1-img3.jpg\" alt=\"\" class=\"img-border\">\n");
      out.write("                    <p>blablabla</p>\n");
      out.write("                    <a href=\"#\" class=\"button\">Plus</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"clear\"></div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"aside\">\n");
      out.write("            <div class=\"container_12\">\t\n");
      out.write("                <div class=\"grid_12\">\n");
      out.write("                    <div class=\"pad-2 block-2 wrap\">\n");
      out.write("                        <div>\n");
      out.write("                            <h3 class=\"p3\">blabla</h3>\n");
      out.write("                            <p class=\"p4\">fmvqjnfvÃ¹qnvÃ¹qknfvÃ¹lknfÃ¹vndsÃ¹f</p>\n");
      out.write("                            <a href=\"#\" class=\"button\">Plus</a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"last\">\n");
      out.write("                            <h3 class=\"p3\">blabla</h3>\n");
      out.write("                            <p class=\"p4\">blaazdmoznfmoenfmjnzeozerv</p>\n");
      out.write("                            <a href=\"#\" class=\"button\">Plus</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"clear\"></div>\n");
      out.write("            </div>\n");
      out.write("        </div>  \n");
      out.write("    </section> \n");
      out.write("  </div>    \n");
      out.write("<!--==============================footer=================================-->\n");
      out.write("    <footer>\n");
      out.write("        <p>Â© 2014 iSchool</p>\n");
      out.write("        <p>Website project by <a href=\"http://ibisc.fr\" target=\"_blank\" rel=\"nofollow\">Evry University</a></p>\n");
      out.write("    </footer>\t    \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
